### ISSUE TITLE
xmlhttprequest error

### ISSUE THREAD

**Issue by pieterdv** [beeman/angular-cli-jest#1]
Hi,

I was trying to get Jest working with Angular2 and stumbled upon your repository, I wrote a test application on my own but I stumbled on 

![image](https://cloud.githubusercontent.com/assets/1443286/23399662/4aec7b8e-fda1-11e6-8460-3a04804145ac.png)

I cloned your repo, ran yarn test but I get the same error 

![image](https://cloud.githubusercontent.com/assets/1443286/23399615/199a8094-fda1-11e6-9663-440518f44d23.png)

any idea how to fix this?

**Comment by beeman** [comment]
@pieterdv I have upgraded the repo with the jest-preset-angular. Can you check if the issue still exists after updating? Thanks

**Comment by pieterdv** [comment]
Issue is resolved with jest-preset-angular! Thanks!
