### ISSUE TITLE
Errors when running yarn test

### ISSUE THREAD

**Issue by ramaghanta** [beeman/angular-cli-jest#3]
Thanks for the sample repo with jest integrated. When I cloned the repo and ran yarn test, I get the following errors. Any ideas?

<img width="1236" alt="screen shot 2017-08-01 at 12 51 59 pm" src="https://user-images.githubusercontent.com/17455213/28836754-40985f28-76b8-11e7-9208-8f8241af2b48.png">

**Comment by abdulhaq-e** [comment]
I upgraded to the latest angular and the tests work fine.
